name: Pre-commit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-pre-commit.yml@master
    with:
      ros_distro: rolling
