name: Rolling Stack Build
# author: Christoph Froehlich <christoph.froehlich@ait.ac.at>
# description: 'Build the stack.'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/rolling-stack-build.yml'
      - 'ros_controls.rolling.repos'

jobs:
  stack-build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: rolling
      ros_repo: testing
      target_workspace: ros_controls.rolling.repos
      ref_for_scheduled_build: master
      not_test_build: true
